apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cernity-env
  labels:
    {{- include "cernity.labels" . | nindent 4 }}
data:
  REDPANDA_BOOTSTRAP: {{ .Values.bus.bootstrap | quote }}
  NDR_STATE_BACKEND: "redis"
  NDR_REDIS_URL: {{ .Values.state.redisUrl | quote }}
  NDR_TENANT: {{ .Values.tenant | quote }}
  WINDOW_SECS: {{ .Values.windowSecs | quote }}
  EVAL_SECS: {{ .Values.evalSecs | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  {{- if .Values.clickhouse.enabled }}
  CLICKHOUSE_HOST: {{ .Values.clickhouse.host | quote }}
  CLICKHOUSE_USER: {{ .Values.clickhouse.user | quote }}
  {{- end }}
